module ZSpec where

import Data.Word

_ZEBRA_INTERFACE_ADD = 1 :: Word16
_ZEBRA_INTERFACE_DELETE = 2 :: Word16
_ZEBRA_INTERFACE_ADDRESS_ADD = 3 :: Word16
_ZEBRA_INTERFACE_ADDRESS_DELETE = 4 :: Word16
_ZEBRA_INTERFACE_UP = 5 :: Word16
_ZEBRA_INTERFACE_DOWN = 6 :: Word16
_ZEBRA_IPV4_ROUTE_ADD = 7 :: Word16
_ZEBRA_IPV4_ROUTE_DELETE = 8 :: Word16
_ZEBRA_IPV6_ROUTE_ADD = 9 :: Word16
_ZEBRA_IPV6_ROUTE_DELETE = 10 :: Word16
_ZEBRA_REDISTRIBUTE_ADD = 11 :: Word16
_ZEBRA_REDISTRIBUTE_DELETE = 12 :: Word16
_ZEBRA_REDISTRIBUTE_DEFAULT_ADD = 13 :: Word16
_ZEBRA_REDISTRIBUTE_DEFAULT_DELETE = 14 :: Word16
_ZEBRA_IPV4_NEXTHOP_LOOKUP = 15 :: Word16
_ZEBRA_IPV6_NEXTHOP_LOOKUP = 16 :: Word16
_ZEBRA_IPV4_IMPORT_LOOKUP = 17 :: Word16
_ZEBRA_IPV6_IMPORT_LOOKUP = 18 :: Word16
_ZEBRA_INTERFACE_RENAME = 19 :: Word16
_ZEBRA_ROUTER_ID_ADD = 20 :: Word16
_ZEBRA_ROUTER_ID_DELETE = 21 :: Word16
_ZEBRA_ROUTER_ID_UPDATE = 22 :: Word16
_ZEBRA_HELLO = 23 :: Word16
_ZEBRA_IPV4_NEXTHOP_LOOKUP_MRIB = 24 :: Word16
_ZEBRA_VRF_UNREGISTER = 25 :: Word16
_ZEBRA_INTERFACE_LINK_PARAMS = 26 :: Word16
_ZEBRA_NEXTHOP_REGISTER = 27 :: Word16
_ZEBRA_NEXTHOP_UNREGISTER = 28 :: Word16
_ZEBRA_NEXTHOP_UPDATE = 29 :: Word16
_ZEBRA_MESSAGE_MAX = 30 :: Word16
